version: '2'
services:
  database:
    image: mysql:latest
    env_file: server/.env
    environment:
      MYSQL_DATABASE: proximo
    ports:
      - "3306:3306"

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    volumes:
      - ./server:/usr/src/app
    ports:
      - 3000:3000
    command: sh /usr/src/app/start-server.sh
    links:
      - database

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    volumes:
      - ./server/client:/usr/src/app
    command: npm run start:watch
