version: '2'
services:
  database:
    image: mysql:latest
    env_file: .env
    environment:
      MYSQL_DATABASE: proximo
    ports:
      - "3306:3306"

  server:
    build: .
    volumes:
      - ./client:/usr/src/app/client
      - ./config:/usr/src/app/config
      - ./migrations:/usr/src/app/migrations
      - ./models:/usr/src/app/models
      - ./server:/usr/src/app/server
    ports:
      - 3000:3000
    command: sh /usr/src/app/start.sh
    links:
      - database

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    volumes:
      - ./client:/usr/src/app
    command: npm run start:watch
